server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: dk100:1111
service-url:
  nacos-user-service: http://nacos-payment-provider




